spring.application.name=grandserve1
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/grantserve
spring.datasource.username=root
spring.datasource.password=ROOT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=Y2Y4ZTM1YmYtYjYyMC00ZDllLTlhZTMtZDY2ZDU4ZTMxZmE5Cg==

# Tells Spring to automatically create the session tables on startup
spring.session.jdbc.initialize-schema=always

spring.cache.cache-names=activeGrants
spring.cache.caffeine.spec=expireAfterWrite=1m,maximumSize=100